services:
  elasticsearch:
    build: .
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9201:9200
    volumes:
      - data01:/usr/share/elasticsearch/logs
      - data01:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - 5601:5601
  filebeat:
    build:
      context: .
      dockerfile: ./filebeat/Dockerfile
    volumes:
      - data01:/usr/share/elasticsearch/logs

volumes:
  data01:
    driver: "local"
