#https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-reference-yml.html
filebeat.modules:
- module: elasticsearch

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/elasticsearch/logs/docker-cluster_index_search_slowlog.log

# FilebeatのConfig設定
filebeat.config.modules:
  enabled: true
  path: ${path.config}/modules.d/*.yml

# Output先の設定
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "slowlog-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.template.name: "slowlog"
setup.template.pattern: "slowlog-*"

setup.kibana:
  host: "kibana:5601"
